# Generated by Django 4.2.2 on 2023-06-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_hotels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'managed': True},
        ),
    ]
